# Generated by Django 5.1.4 on 2024-12-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("streaming", "0003_userlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlist",
            name="movies",
        ),
        migrations.AddField(
            model_name="userlist",
            name="movies_id",
            field=models.ManyToManyField(
                related_name="user_list", to="streaming.movie"
            ),
        ),
    ]
