# Generated by Django 5.1.1 on 2024-12-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_remove_userlist_movies_userlist_movies_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_series',
            field=models.BooleanField(default=False),
        ),
    ]
